INSERT INTO [dbo].[enrollee] (
	[starttime],
	[startdate],
	[deviceid],
	[deviceid2],
	[mrc],
	[subjid],
	[district],
	[mayuge_warning],
	[busia_warning],
	[subcounty],
	[parish],
	[village],
	[placeofresidence],
	[dob],
	[age_calculated],
	[agemonths_calculated],
	[age_at_apr2025],
	[age_in_range],
	[age],
	[agemonths],
	[age_eligible],
	[age_warning],
	[age_warning_reason],
	[mal_test_eligible],
	[ill_noteligible],
	[consent_eligible],
	[participantsname],
	[gender],
	[hhheadeduclevel],
	[diagnostic],
	[result],
	[vx_card],
	[vx_card_no],
	[vx_card_no_oth],
	[vx_any],
	[vx_any_no],
	[vx_any_no_oth],
	[vx_doses_received],
	[vx_doses_received_ver],
	[vx_doses_received_ver_oth],
	[vx_dose1_where],
	[vx_dose1_where_oth],
	[vx_dose1_date],
	[vx_dose1_date_ver],
	[vx_dose1_date_ver_oth],
	[vx_dose2_where],
	[vx_dose2_where_oth],
	[vx_dose2_date],
	[dose2_warning_time],
	[vx_dose2_datecheck],
	[vx_dose2_date_ver],
	[vx_dose2_date_ver_oth],
	[vx_dose3_where],
	[vx_dose3_where_oth],
	[vx_dose3_date],
	[dose3_warning_time],
	[vx_dose3_datecheck],
	[vx_dose3_date_ver],
	[vx_dose3_date_ver_oth],
	[vx_dose4_where],
	[vx_dose4_where_oth],
	[vx_dose4_date],
	[dose4_warning_time],
	[vx_dose4_datecheck],
	[vx_dose4_date_ver],
	[vx_dose4_date_ver_oth],
	[vx_dose_summary],
	[vx_doses_miss],
	[vx_doses_miss_reas],
	[vx_doses_miss_reas_oth],
	[vx_dose_off_sched],
	[vx_doses_offsched_reas],
	[vx_offsched_miss_reas_oth],
	[hib_any],
	[hib_doses_received],
	[hib_doses_received_ver],
	[hib_doses_received_ver_oth],
	[hib_dose1_where],
	[hib_dose1_where_oth],
	[hib_dose1_date],
	[hib_dose1_date_ver],
	[hib_dose1_date_ver_oth],
	[hib_dose2_where],
	[hib_dose2_where_oth],
	[hib_dose2_date],
	[hibdose2_warning_time],
	[hib_dose2_datecheck],
	[hib_dose2_date_ver],
	[hib_dose2_date_ver_oth],
	[hib_dose3_where],
	[hib_dose3_where_oth],
	[hib_dose3_date],
	[hibdose3_warning_time],
	[hib_dose3_datecheck],
	[hib_dose3_date_ver],
	[hib_dos32_date_ver_oth],
	[hib_dose_summary],
	[timetobed],
	[spray],
	[bednetlastnight],
	[bednettwoweeks],
	[prevdiag],
	[prevdiag_when],
	[prevdiag_lastmonth],
	[prevdiag_al],
	[prevdiag_othermeds],
	[prevdiag_descothermed],
	[consent],
	[consent2],
	[uid],
	[uid2],
	[fpbarcode1_r21],
	[fpbarcode2_r21],
	[enroll_immrse],
	[fpbarcode1_immrse],
	[fpbarcode2_immrse],
	[comments],
	[uniqueid],
	[swver],
	[survey_id],
	[lastmod],
	[stoptime]
)
SELECT 
	CAST(NULLIF(REPLACE([starttime], 'T', ' '), '') AS datetime2(6)),
	CAST(NULLIF([startdate], '') AS date),
	NULLIF([deviceid], ''),
	NULLIF([deviceid2], ''),
	NULLIF([mrc], ''),
	NULLIF([subjid], ''),
	CAST(NULLIF([district], '') AS int),
	CAST(NULLIF([mayuge_warning], '') AS int),
	CAST(NULLIF([busia_warning], '') AS int),
	NULLIF([subcounty], ''),
	NULLIF([parish], ''),
	NULLIF([village], ''),
	NULLIF([placeofresidence], ''),
	CAST(NULLIF([dob], '') AS date),
	CAST(NULLIF([age_calculated], '') AS int),
	CAST(NULLIF([agemonths_calculated], '') AS int),
	CAST(NULLIF([age_at_apr2025], '') AS int),
	CAST(NULLIF([age_in_range], '') AS int),
	CAST(NULLIF([age], '') AS int),
	CAST(NULLIF([agemonths], '') AS int),
	CAST(NULLIF([age_eligible], '') AS int),
	CAST(NULLIF([age_warning], '') AS int),
	NULLIF([age_warning_reason], ''),
	CAST(NULLIF([mal_test_eligible], '') AS int),
	CAST(NULLIF([ill_noteligible], '') AS int),
	CAST(NULLIF([consent_eligible], '') AS int),
	NULLIF([participantsname], ''),
	CAST(NULLIF([gender], '') AS int),
	CAST(NULLIF([hhheadeduclevel], '') AS int),
	CAST(NULLIF([diagnostic], '') AS int),
	CAST(NULLIF([result], '') AS int),
	CAST(NULLIF([vx_card], '') AS int),
	CAST(NULLIF([vx_card_no], '') AS int),
	NULLIF([vx_card_no_oth], ''),
	CAST(NULLIF([vx_any], '') AS int),
	CAST(NULLIF([vx_any_no], '') AS int),
	NULLIF([vx_any_no_oth], ''),
	NULLIF([vx_doses_received], ''),
	CAST(NULLIF([vx_doses_received_ver], '') AS int),
	NULLIF([vx_doses_received_ver_oth], ''),
	CAST(NULLIF([vx_dose1_where], '') AS int),
	NULLIF([vx_dose1_where_oth], ''),
	CAST(NULLIF([vx_dose1_date], '') AS date),
	CAST(NULLIF([vx_dose1_date_ver], '') AS int),
	NULLIF([vx_dose1_date_ver_oth], ''),
	CAST(NULLIF([vx_dose2_where], '') AS int),
	NULLIF([vx_dose2_where_oth], ''),
	CAST(NULLIF([vx_dose2_date], '') AS date),
	CAST(NULLIF([dose2_warning_time], '') AS int),
	CAST(NULLIF([vx_dose2_datecheck], '') AS int),
	CAST(NULLIF([vx_dose2_date_ver], '') AS int),
	NULLIF([vx_dose2_date_ver_oth], ''),
	CAST(NULLIF([vx_dose3_where], '') AS int),
	NULLIF([vx_dose3_where_oth], ''),
	CAST(NULLIF([vx_dose3_date], '') AS date),
	CAST(NULLIF([dose3_warning_time], '') AS int),
	CAST(NULLIF([vx_dose3_datecheck], '') AS int),
	CAST(NULLIF([vx_dose3_date_ver], '') AS int),
	NULLIF([vx_dose3_date_ver_oth], ''),
	CAST(NULLIF([vx_dose4_where], '') AS int),
	NULLIF([vx_dose4_where_oth], ''),
	CAST(NULLIF([vx_dose4_date], '') AS date),
	CAST(NULLIF([dose4_warning_time], '') AS int),
	CAST(NULLIF([vx_dose4_datecheck], '') AS int),
	CAST(NULLIF([vx_dose4_date_ver], '') AS int),
	NULLIF([vx_dose4_date_ver_oth], ''),
	CAST(NULLIF([vx_dose_summary], '') AS int),
	CAST(NULLIF([vx_doses_miss], '') AS int),
	CAST(NULLIF([vx_doses_miss_reas], '') AS int),
	NULLIF([vx_doses_miss_reas_oth], ''),
	CAST(NULLIF([vx_dose_off_sched], '') AS int),
	CAST(NULLIF([vx_doses_offsched_reas], '') AS int),
	NULLIF([vx_offsched_miss_reas_oth], ''),
	CAST(NULLIF([hib_any], '') AS int),
	NULLIF([hib_doses_received], ''),
	CAST(NULLIF([hib_doses_received_ver], '') AS int),
	NULLIF([hib_doses_received_ver_oth], ''),
	CAST(NULLIF([hib_dose1_where], '') AS int),
	NULLIF([hib_dose1_where_oth], ''),
	CAST(NULLIF([hib_dose1_date], '') AS date),
	CAST(NULLIF([hib_dose1_date_ver], '') AS int),
	NULLIF([hib_dose1_date_ver_oth], ''),
	CAST(NULLIF([hib_dose2_where], '') AS int),
	NULLIF([hib_dose2_where_oth], ''),
	CAST(NULLIF([hib_dose2_date], '') AS date),
	CAST(NULLIF([hibdose2_warning_time], '') AS int),
	CAST(NULLIF([hib_dose2_datecheck], '') AS int),
	CAST(NULLIF([hib_dose2_date_ver], '') AS int),
	NULLIF([hib_dose2_date_ver_oth], ''),
	CAST(NULLIF([hib_dose3_where], '') AS int),
	NULLIF([hib_dose3_where_oth], ''),
	CAST(NULLIF([hib_dose3_date], '') AS date),
	CAST(NULLIF([hibdose3_warning_time], '') AS int),
	CAST(NULLIF([hib_dose3_datecheck], '') AS int),
	CAST(NULLIF([hib_dose3_date_ver], '') AS int),
	NULLIF([hib_dos32_date_ver_oth], ''),
	CAST(NULLIF([hib_dose_summary], '') AS int),
	CAST(NULLIF([timetobed], '') AS int),
	CAST(NULLIF([spray], '') AS int),
	CAST(NULLIF([bednetlastnight], '') AS int),
	CAST(NULLIF([bednettwoweeks], '') AS int),
	CAST(NULLIF([prevdiag], '') AS int),
	CAST(NULLIF([prevdiag_when], '') AS int),
	CAST(NULLIF([prevdiag_lastmonth], '') AS int),
	CAST(NULLIF([prevdiag_al], '') AS int),
	CAST(NULLIF([prevdiag_othermeds], '') AS int),
	NULLIF([prevdiag_descothermed], ''),
	CAST(NULLIF([consent], '') AS int),
	CAST(NULLIF([consent2], '') AS int),
	NULLIF([uid], ''),
	NULLIF([uid2], ''),
	NULLIF([fpbarcode1_r21], ''),
	NULLIF([fpbarcode2_r21], ''),
	CAST(NULLIF([enroll_immrse], '') AS int),
	NULLIF([fpbarcode1_immrse], ''),
	NULLIF([fpbarcode2_immrse], ''),
	NULLIF([comments], ''),
	NULLIF([uniqueid], ''),
	NULLIF([swver], ''),
	NULLIF([survey_id], ''),
	CAST(NULLIF(REPLACE([lastmod], 'T', ' '), '') AS datetime2(6)),
	CAST(NULLIF(REPLACE([stoptime], 'T', ' '), '') AS datetime2(6))
FROM [dbo].[enrollee_staging]
